### ISSUE TITLE
Problem with snoop, some parameter use Enumerator

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#1]
Whether we have any update for this, all field use Enumerator have same issue.
![image](https://user-images.githubusercontent.com/31106432/152712606-0f584fb3-a976-4dab-a6b5-d116f1bbd309.png)

**Comment by weianweigan** [comment]
Yes,i write some code to fix this.But i am a new developer in revit,you can check the code i commited.

![image](https://user-images.githubusercontent.com/25452811/152961517-1c6bc804-7185-478b-8942-f03933d4149b.png)

**Comment by chuongmep** [comment]
I have a few pull requests to fix bugs and build something and create an installer msi automatic, would you mind letting me do that?

**Comment by weianweigan** [comment]
I am very glad that you want to make a installer and fix bugs for this project.Thank you and I invited you as a collaborators just now.

**Comment by chuongmep** [comment]
Appreciate your source code and enthusiasm.
