### ISSUE TITLE
Need Support Snoop Element with method have list or icollection return element id inside

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#10]
Idea : When user click to this, it will show new window and show info of element of list element.
Example : GetMaterialsIds() , GetTypeId(),...
![image](https://user-images.githubusercontent.com/31106432/153535386-6a38c705-8f9e-4dbc-bd72-417a1f938b05.png)
![image](https://user-images.githubusercontent.com/31106432/153535706-376276e3-3aa4-4131-8e4e-2469a3b7ab01.png)

**Comment by weianweigan** [comment]
When a method has no parameter,we can invoke to get a value as we do in #4 .But when a method has some parameters and this parameters are all value type, weather we can let user input some parameters to get a value?
I am trying to find some way...

**Comment by chuongmep** [comment]
I think we don't need do that for all method, we need only selection some method support as GetTypeId() to check element id, may be i will create a form for user support input elementid or guid to snoop.
With that, when a method return a elementid or list element id, we can continute use doc.getElement(elementid) to snoop this element.
Example with single element : 
- Snoop element
- Press to GetTypeId() => return ElementId (1)
- When click to GetTypeId() => Snoop element doc.GetElement(1) to continute show it.
