### ISSUE TITLE
Input parameters to get a value

### ISSUE THREAD

**Issue by weianweigan** [weianweigan/RevitLookupWpf#17]
**Is your feature request related to a problem? Please describe.**
Some properties or methods need parameters to get a value

**Describe the solution you'd like**
Add a dropdown panel for user to input some value they konw.

![image](https://user-images.githubusercontent.com/25452811/154008874-3e650ff8-c7af-4fd3-b772-0fe89538cbec.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by chuongmep** [comment]
that good idea, i support it.

**Comment by weianweigan** [comment]
I commited code,  you can take a look at #18
