### ISSUE TITLE
Add MSI Automatic, improve code base long time support .NET 6

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#2]
Dear @weianweigan 
I have completed all the major work on the automation and rebuilt some of the main content as follows:

- [x] Automatic Build MSI installer, use branch dev to developer and branch master to release version.
- [x] Change Ribbon to tab Addin-Ins  to sync with available developer tools.
- [x] Change to .NET 6 for long term support by Microsoft.
- [x] Add Read me, change some picture demo
- [x] Add Change Log 
- [x] Fix small problem with show image button.
- [x] Change language message to English.
- [x] Fix NameSpace Conflict with RevitLookup use windows form.

I will continue to improve a few points if necessary. Now you can delete main branch(or rename to backup ), change priority branch to dev branch everything will work perfectly.

![image](https://user-images.githubusercontent.com/31106432/153045289-592ace52-07c1-4065-bb65-ee9cb0a6cbf1.png)

Best Regards !

**Comment by weianweigan** [comment]
Thanks for your excellent work! I switched dev as default branch and delete main branch.It's cool to use nuke to finished a CD/CI work.
