### ISSUE TITLE
Search online api doc

### ISSUE THREAD

**Issue by weianweigan** [weianweigan/RevitLookupWpf#20]
Hi @chuongmep , Thanks for your work. 
I found your [commit](https://github.com/weianweigan/RevitLookupWpf/commit/0840d80fbc9b1cc40fab954e7865b265fff54856) about search in [revitapidoc](revitapidocs.com). I take a look at the website.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/25452811/154044376-98109b62-1d85-4757-9585-1f712ca877ef.png">

Each page has a guid in it's url, can we find a match about this?
 If there is a match in guid and api, can we directly open the url rather than search it?

I found a [link](https://github.com/gtalarico/revitapidocs/issues/97) about this in github,you can take a look.

**Comment by chuongmep** [comment]
@weianweigan let me find relate guid it and confirm with you.At the moment it only search by query.

**Comment by chuongmep** [comment]
my idea is crawl all data from website include guid,version,methodname,class,namespace save to json, we will read data and search in file json that.

**Comment by chuongmep** [comment]
This id from file chm of autodesk
![image](https://user-images.githubusercontent.com/31106432/154061549-9b4fc39c-2e60-4a83-95a4-4aa5879c1323.png)

**Comment by chuongmep** [comment]
@weianweigan you can return value this in project with method or properties ?
![image](https://user-images.githubusercontent.com/31106432/154069361-7c3d93e7-ad09-474d-9741-e38da353066d.png)

**Comment by chuongmep** [comment]
@weianweigan We can do that, but first, may be i will create a new project other to gen file json, next you can use file json it to get description or guid to open online, you have any idea ?
![image](https://user-images.githubusercontent.com/31106432/154105363-8602fe3c-b025-459c-849a-cddd21a754cb.png)

**Comment by chuongmep** [comment]
i will try save it to json, we can use data map to get description of method or properties.Next some guid will be map to go to online link
![image](https://user-images.githubusercontent.com/31106432/154107360-a419639f-319c-4cb9-9c1a-b7efffdbf4ac.png)

**Comment by weianweigan** [comment]
Wow ,it'amazing that you did it so efficiently.

**Comment by chuongmep** [comment]
> Wow ,it'amazing that you did it so efficiently.

whether we can custom again PropertyBase include like that ?
```
 {
        "Title":"DoorCost",
        "Keywords":"ParameterTypeId.DoorCost property",
        "APIName":"P:Autodesk.Revit.DB.ParameterTypeId.DoorCost.DoorCost",
        "Description":"\"Cost\"",
        "Namespace":"Autodesk.Revit.DB",
        "Guid":"efdf5191-47a5-2d99-db4f-b425edebbee6",
        "Type":"property"
    }
```

**Comment by weianweigan** [comment]
Yes，we can add some properties to propertybase. Perhaps we can add a new class to store and map and easy deserialization.
Either is ok.

**Comment by chuongmep** [comment]
I had add example to [project RevitAPIDocGen ](https://github.com/chuongmep/RevitAPIDocGen), may be will waiting you add properties in propertybase before I add this feature, I will use from it to map and search.

**Comment by weianweigan** [comment]
Ok,i will do.
