### ISSUE TITLE
Element Type not show name

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#36]
**Describe the bug**
Wall Type not show name correct

**To Reproduce**
1. Go to snoop wall
2. Click on method gettypeid
3. Scroll down to name

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/154850930-779b93e1-1620-4475-8f07-a671e8d9c7f2.png)

**Additional context**

**Comment by weianweigan** [comment]
The Name Property in [WallType](https://www.revitapidocs.com/2022/6b3f1f32-725f-0ec8-dcdd-75373654d3a2.htm) class is a set only property,it don't have a get method to invoke. 

![image](https://user-images.githubusercontent.com/25452811/154899611-96f4e159-6eb5-49fa-97f5-38c449da9d9a.png)

<img width="713" alt="image" src="https://user-images.githubusercontent.com/25452811/154899776-192b62ba-0ebd-4e1d-bc86-099c573895bd.png">

**Comment by chuongmep** [comment]
whether we can replace result it by way WallType(428955).Name ?

**Comment by weianweigan** [comment]
WallType.Name is also a set only property. Can i get the result from it ?  I have a little uncertain.

**Comment by chuongmep** [comment]
Yes, it can return a name of elementtype, you can try :
[![image](https://user-images.githubusercontent.com/31106432/154902605-f1a61416-685d-4712-9eb4-7b6381f89fbe.png)](https://github.com/weianweigan/RevitLookupWpf/blob/d7511a490850be67ba70ac07c80e75191342b43e/RevitLookup/Commands/SnoopTestCommand.cs#L25-L31)

**Comment by weianweigan** [comment]
Thanks! I test it and get a result.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/25452811/154906405-f267486a-62a9-4166-8382-c41ab1c75810.png">

**Comment by chuongmep** [comment]
awesome, result is clear !
