### ISSUE TITLE
Need design again document to use snoop doc linked

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#37]
**Describe the bug**
when we use static external command data from here, if user snoop element inside linked, we can't use document from linked model to execute method or properties from feature #10 

https://github.com/weianweigan/RevitLookupWpf/blob/ab71b3592e44fbb8c909cc759ea175ac79bfb4ec/RevitLookup/SnoopingContext.cs#L21-L24

you have any idea to can execute function with element inside linked ?

**Comment by weianweigan** [comment]
Yes, the snoopcontext is not a good design. I need take a think.
