### ISSUE TITLE
Problem with toggle dropdown

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#38]
**Describe the bug**
Toggle dropdown not change between two mode open or close when press

**Expected behavior**

**Screenshots**
![Revit_LA87ZBlUa3](https://user-images.githubusercontent.com/31106432/154888433-4878e1c7-f0c4-4d69-9b29-702b6532229d.gif)

**Additional context**

**Comment by weianweigan** [comment]
Thanks for your test. I will fix it.

**Comment by weianweigan** [comment]
> Thanks for your test. I will fix it.

I tested it and i cannot find a way to fix it. In another side, combobox has same behavior in wpf. So just let it go!
