### ISSUE TITLE
Show Value In Datagrid ? 

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#4]
Hi @weianweigan 
whether we can add a column or have any way(solution) to show result of some value some thing like that ? 
![image](https://user-images.githubusercontent.com/31106432/153366723-b9017522-1745-48cf-bb32-9c04dfc238e0.png)

**Comment by weianweigan** [comment]
Yes, we can display it's value directly when the method return a value type. In my another [lookup tool](https://github.com/weianweigan/SolidWorksLookup), i changed cell's value and color to show value.

![image](https://user-images.githubusercontent.com/25452811/153530829-bd34cfaf-daf1-4fb4-a9a2-b9f3161e5e58.png)

When user click the cell  GetArea(),the the cell'value will changed.

![image](https://user-images.githubusercontent.com/25452811/153531027-d4ce9276-d486-44cf-a0db-95c84c659398.png)

If you agree with this way, i will add this feature. Do you have a another idea?

**Comment by chuongmep** [comment]
nice idea , i agree with this way , do they also automatically show null value if nothing ?

**Comment by chuongmep** [comment]
Some thing like that, it automatic return null if invoke method return null or empty
![image](https://user-images.githubusercontent.com/31106432/153532433-c95884a4-b164-4595-8b0c-8b6e539f694e.png)

**Comment by weianweigan** [comment]
If it's null,It should be works like this, but i am not very sure.

**Comment by chuongmep** [comment]
wow, look awesome, may be problem #10 same with this, you can take a look at this error.

**Comment by weianweigan** [comment]
Blue is ok and performs good than before.
