### ISSUE TITLE
error with properties return value enum

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#42]
**Describe the bug**
all mark return enum error because it have value.

**To Reproduce**
1. Go to Snoop family instance

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/154994049-5315d122-ae1c-4eb5-8a80-366a0f72447f.png)

**Comment by weianweigan** [comment]
Yes, there is not a class to match Enum type now. I will add it.
