### ISSUE TITLE
Boundingbox,View still have use some method have get_ or set_

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#43]
**Describe the bug**

**Screenshots**
Boudingbox
![image](https://user-images.githubusercontent.com/31106432/154999144-64de2120-7be0-428f-a0c6-54d783903bf1.png)
View
![image](https://user-images.githubusercontent.com/31106432/155057850-b11690dd-894b-4df8-b4a4-f4576b5175b2.png)

**Comment by weianweigan** [comment]
Some classes have get_? or set_? method. I think the method may be equal a property, so I filter it.

https://github.com/weianweigan/RevitLookupWpf/blob/c4777e1182046c0697fd3117d41470186bdb14fe/RevitLookup/Extension/ObjectExtension.cs#L56-L62

I don't konw if it is useful, i usually use the property either get_ or set_.

**Comment by chuongmep** [comment]
thanks , we will ignore it , I agree this.
