### ISSUE TITLE
add convert unit value

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#47]
**Is your feature request related to a problem? Please describe.**
@weianweigan I have idea, whether we can add some drop down here with option convert unit if value return is doube or int or string like 10m3 from library of revit units ?

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/31106432/156708086-dd0d58c7-c68d-4759-9258-bae443e2d826.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by weianweigan** [comment]
Sorry to reply you so late!
I don't use revit in my daily work, but It's a good idea to convert unit with options in my opinion.You work in bim area so you can add some feature directly if you want.
Thanks for your work.

**Comment by chuongmep** [comment]
Thanks so much,  I'll do it and make a pull request when I have some time over the weekend.

**Comment by chuongmep** [comment]
Resolve #55
