### ISSUE TITLE
Need allow go back to before selected or open other window.

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#5]
![image](https://user-images.githubusercontent.com/31106432/153410379-45818f2b-e314-40e6-9b68-6c3716dd36b7.png)

**Comment by chuongmep** [comment]
i think should allow user to open multiple windows at the same time to compare values.

**Comment by weianweigan** [comment]
I agree with this.I want to add contextmenu to the row or cell in datagrid, so user can right click and then choose open in new window command.

**Comment by chuongmep** [comment]
can we span previous operations, it seems the back button is more inconvenient than this, we can limit 4 to 5 items maximum
![image](https://user-images.githubusercontent.com/31106432/153533490-20d99f83-a4b7-4df1-9451-773dc3184450.png)

**Comment by weianweigan** [comment]
I am sorry about this. It's a bug that only two item displayed in navigation bar. I will fix this and it will allow a long history recorded in navigation bar.

**Comment by chuongmep** [comment]
We have this tool to work with fast reloading of assemblies, if you need to speed this up, I'm working on that project.
https://github.com/chuongmep/RevitAddInManager
![image](https://user-images.githubusercontent.com/31106432/153536622-0c6201e8-8414-4f1e-bb3a-1e8ab3a612d4.png)

**Comment by weianweigan** [comment]
Thanks a lot, it looks handsome
