### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by weianweigan** [weianweigan/RevitLookupWpf#51]
**Is your feature request related to a problem? Please describe.**
The icon used now from [iconfont](https://www.iconfont.cn/).I don't konw if there is a license problem.

**Describe the solution you'd like**
I design a new icon followed revit's new icon style after 2022.
![RevitLookupWpf (2)](https://user-images.githubusercontent.com/25452811/184874525-ee031c66-45ec-4006-aa09-b7782727eca5.png)

**Describe alternatives you've considered**
None.

**Additional context**
I want to use new icon in my next pr or is there some other suggestions?

**Comment by chuongmep** [comment]
It look so good , let do it.
