### ISSUE TITLE
Problem when snoop to boudingbox element

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#9]
![image](https://user-images.githubusercontent.com/31106432/153534907-2daf94e5-0b7e-41fd-b8ad-c41b9d874504.png)

**Comment by weianweigan** [comment]
I input a current view to get the result. 

```csharp
CommandData.View
```

I don't konw weather i can get all of the views in doc.

![image](https://user-images.githubusercontent.com/25452811/154009849-ac5e034a-0fce-4b0f-9c37-35846364fdde.png)

![image](https://user-images.githubusercontent.com/25452811/154010062-2bd3607f-ebab-449d-b8ab-e6477fc6d3d4.png)

**Comment by chuongmep** [comment]
> 
no need with boudingbox, we can input null is default to getboudingbox,
Example : 
element.GetBoudingbox(null);

**Comment by weianweigan** [comment]
amazing,i don't know about this.

**Comment by chuongmep** [comment]
whether we can set defaul is null for user ? we still use dropdown if user cannot get boudingbox with value null.

**Comment by chuongmep** [comment]
> 
we can get all view in doc, use some like that
```
private List<View> view;
        public List<View> AllViews
        {
            get
            {
                if (view == null)
                    view = new List<Element>(new FilteredElementCollector(doc)
                            .OfClass(typeof(View)).WhereElementIsNotElementType().ToList().OrderBy(v => v.Name)).Distinct()
                        .ToList().Cast<View>().ToList().Where(x => !x.Name.Contains($"<Revision Schedule>")).Where(x => !x.IsTemplate).ToList();
                return view;
            }
            set
            {
                view = value;
            }
        }
```

**Comment by weianweigan** [comment]
Yes,we can set default value as null, let me take a try.
